### ISSUE TITLE
Create Review button does not appear ingame

### ISSUE THREAD

**Issue by LumaLivy** [LBPUnion/ProjectLighthouse#107]
Reviews are now implemented in the game as of #102, which closes #27, but creating reviews is a bit scuffed. 

To allow review uploads, I made a workaround that involves having the server send an empty "fake" review to the player upon playing a level, so that they may edit the review and force the review to upload (the same endpoint is called for editing a review/uploading one). This way, only the player can see their empty "fake" review and no one else can, until the review is uploaded. The fake review is not stored in the database until it is uploaded as a real review either. It's basically a convoluted way of allowing the user to open the review editor in-game.

Ideally, a way is found to re-enable the "Leave a Review!" button in-game, which will prompt the review editor to open without having to edit an existing review. The button may be hidden due to a missing network configuration option, or missing data in the XML schema, but the true reason is not yet known.

**Comment by turecross321** [comment]
seems to have been fixed in https://github.com/LBPUnion/ProjectLighthouse/pull/145#issue-1124877480

(only tried on lbp vita but i assume the same goes for the other games)

**Comment by jvyden** [comment]
I tested on LBP2 earlier and there was no change, so unfortunately not.

I believe this was already working on LBPV.
