### ISSUE TITLE
Add overlays for profile and level thumbnails

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#128]
LBP.me had overlays for level and profile pictures, it would be nice for us to have them too
![minimal_badge_overlay](https://user-images.githubusercontent.com/93880348/152661331-fab2bd04-603e-477f-b78b-b99167537470.png)
https://drive.google.com/file/d/14-EWo5vSX64M5KhrOZ7t8uUe-yNEvS7A/view?usp=sharing

**Comment by jvyden** [comment]
We cant use those assets because we dont own them. Sorry.

**Comment by Arcadius2006** [comment]
why not make new ones then??????????

**Comment by Arcadius2006** [comment]
watch me make a perfectly fine new overlay for level badges right now

**Comment by Arcadius2006** [comment]
![minimal_badge_overlay](https://user-images.githubusercontent.com/93880348/151600652-d96551a5-d249-492c-8545-df7034ff3f05.png) LOOK AT IT

**Comment by jvyden** [comment]
Please calm down.

Anyways, sure, that looks suitable. I'll look into it.

**Comment by Arcadius2006** [comment]
heck yeah

**Comment by jvyden** [comment]
Can you reupload these in a .zip? I'm pretty sure GitHub is messing with the images.

**Comment by Arcadius2006** [comment]
i can send it to you in discord DMs
