### ISSUE TITLE
No longer works to login to the server on PS VITA npTicket error

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/ProjectLighthouse#129]
When trying to play on Vita after the new update where it should be able to detect which platform you are playing on. It breaks Vita support, the the server gives me the following:

`[Login] npTicket was null, rejecting login`
`[HTTP] 400, 16ms: POST /LITTLEBIGPLANETPS3_XML/login?applicationID=21424&languageID=1&lbp2=1&game=lbp-vita&beta=0&titleID=PCSF00021`

**Comment by jvyden** [comment]
Should be fixed now. Thanks to @turecross321 for the help!
