### ISSUE TITLE
Automatic Account Creation

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#136]
This is something we'll need to think about carefully when approaching a public beta.

- [x] User can create an account without needing an admin to do it for them
- [x] Verify account by email
- [x] Some sort of anti-bot safeguards. Recaptcha, limit total users per IP are some ideas I have but there may be better ways
- [ ] Force user to verify they are over the age of 13 to comply with COPPA.

**Comment by jvyden** [comment]
Users can already create accounts by themselves, it's just that our private instance has registrations disabled.

**Comment by jvyden** [comment]
For the date of birth thing, I would strongly prefer this be done client-side with JavaScript so we aren't handling the data.
