### ISSUE TITLE
SEO-Enhanced Slugs (URLs) 

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#146]
Currently level and profile URLs appear as "slots" or something that doesn't make much sense out of context. These pages stand a chance of ranking higher on Google if they are more descriptive based off of the level or user's name.

For example, this is the difference between,

> https://lighthouse.com/slot/3419

and

> https://lighthouse.com/slot/3D-platforming-logic-showcase

If a level of the same name is published, add a hyphen and then a number to the end. I may need to do some more research on this because similar URLs (from copied levels or levels of the same name) may be bad for a level page's search ranking

**Comment by jvyden** [comment]
Would something like https://lighthouse.com/slot/3104/amazing-level-wow work instead? The way you mentioned seems a bit annoying to handle.

**Comment by m88youngling** [comment]
Yessir!

**Comment by TheManchineel** [comment]
I agree with jvyden, that's also how Reddit does it. I'd make any request to https://lighthouse.com/slot/3104/$level-name check if $level-name is the actual name for 3104, and if not, 302 temporary-redirect to the proper level name.
