### ISSUE TITLE
User highlight broken

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#152]
Photos now always display highlighted photos, it was not like this before
![image](https://user-images.githubusercontent.com/93880348/152704541-2b605b81-cac3-4acb-89c9-478967e82670.png)
![image](https://user-images.githubusercontent.com/93880348/152704558-bacb7b38-2663-45ad-b866-f309dd31ccbd.png)

**Comment by jvyden** [comment]
This is a cache issue. Press Ctrl + F5 to clear it.

**Comment by Arcadius2006** [comment]
i did not even need to clear the cache
