### ISSUE TITLE
Grief Reports fail to submit if it tries to upload an unsafe file

### ISSUE THREAD

**Issue by jvyden** [LBPUnion/ProjectLighthouse#168]
From what I can gather it will attempt to upload relevant files (meshes, models, and other unsafe files we have blocked) when submitting a grief report

So when the option to check for unsafe files is enabled it will attempt to upload all these unsafe files and the grief report will not submit. 

Not sure how I'm going to resolve this.

**Comment by Slendy** [comment]
Is the issue the fact that the client won't even try to submit the grief request or is the server failing to handle the request?

**Comment by jvyden** [comment]
The client won't even try.

**Comment by jvyden** [comment]
It might be weird, but the only real option I can see is lying to the client about whether the assets were uploaded correctly.
