### ISSUE TITLE
Add a way to configure what URL the server listens to

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#169]
When hosting a server on windows right now, the only way you can make other ip-addresses other than localhost able to connect to the server is to modify the `appsettings,json` file, but this flags the system that checks if any files have been modified.

**Comment by jvyden** [comment]
After some thought, you could probably set the `ASPNETCORE_URLS` env variable.
So to listen on all interfaces at port `10060` you could do:
```bash
export ASPNETCORE_URLS=http://0.0.0.0:10060

dotnet run
```

**Comment by jvyden** [comment]
Actually, that's rather inconvenient. Let me do some research.
