### ISSUE TITLE
LBP1 doesn't display user comments

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#176]
i don't know why, but LBP1 refuses to display comments

**Comment by jvyden** [comment]
It appears to be a client-side issue. I'm not getting any requests for comments on the server for some reason.

**Comment by jvyden** [comment]
Posting comments works.

**Comment by jvyden** [comment]
![image](https://user-images.githubusercontent.com/40577357/159075665-88ed24f3-1fb7-41c9-a151-73194b623fda.png)
Page buttons appeared after posting a comment after a refresh of the slot info, but still no requests for comments. :thinking:

**Comment by jvyden** [comment]
![image](https://user-images.githubusercontent.com/40577357/184428301-9c083de3-f99b-4ca9-bb04-adf795e85121.png)

Seems to be fixed as of now, it just took a couple of minutes for LBP1 to decide to fetch the comments.

**Comment by TorutheRedFox** [comment]
yeah it takes a while for some reason
