### ISSUE TITLE
Add ability to upload LBP Vita "slot" files from website.

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#178]
This might be a bit much to ask for in one issue, but it would help to upload old archived levels from the official servers a bunch.

`slot_` files are downloaded levels in LBP Vita. They are FAR4 files and contain things such as a PNG for the level icon, a SLT file for the metadata, and of course, a BIN file which is the actual level. All downloaded levels can be found in the savefile under `output/savegame/`

The feature I'm asking for here is a tool, that can take one of these slot files (or multiple at the same time), and upload it to the server. (through the admin panel in the website for instance)

Having this, it'd be possible to easily upload hundreds of archived LBP Vita levels in just a matter of minutes.

Here is a download link to my own savefile which contains 400+ downloaded levels:
https://drive.google.com/file/d/14TRemtBfX4HwIJrZ_IZt5GKGejdF3n75/view?usp=sharing

![image](https://user-images.githubusercontent.com/51852312/154914695-4029b5b3-c251-4ec5-b700-7f60cebd9260.png)

**Comment by jvyden** [comment]
Closing in favor of #321
