### ISSUE TITLE
LBP Vita Plays do not display.

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#182]
This has only been partly fixed since #60.

![image](https://user-images.githubusercontent.com/51852312/154916179-db3a40dc-2e50-4619-a96b-cde388361310.png)

While both the `Beaten x times` and `Played x times` counters now work, the `by x people` counter displays 0, no matter how many people have played it, and the same goes for the main counter with the plays icon.
![image](https://user-images.githubusercontent.com/51852312/154916520-604e339d-8d66-478f-ad10-6b9df6cfd995.png)

**Comment by jvyden** [comment]
Does [3bedec5](https://github.com/LBPUnion/ProjectLighthouse/commit/3bedec5f70c7b59ef9a62a7effeffc94a7d263a6) help at all with this?

**Comment by turecross321** [comment]
Yep! That fixed it.
