### ISSUE TITLE
Username sanitization

### ISSUE THREAD

**Issue by AShifter** [LBPUnion/ProjectLighthouse#184]
The registration page does not limit the length of a new user's username. As this should be the same as your PSN name, which should not exceed 16 characters (please verify this before committing to a solution), the registration dialogue should limit you to 16 characters.

**Comment by Ezoiar** [comment]
Also restrict any unsupported characters.

**Comment by jvyden** [comment]
Resolved in 7e498d, de6f624, and 9dc296a.
