### ISSUE TITLE
Differentiate Lighthouse accounts from PSN ID and RPCN ID

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/ProjectLighthouse#204]
Some people have constant changing IPs and may have frustrating problems with having to whitelist their new IPs. So if possible, Lighthouse accounts should be their own entity. Let's say for example my lighthouse account was called Example3 my PSNID Example1 and RPCN Example 2. So how the server would know that PSNID Example1 is connected with Example 3 is via a confirmation page. There should be a confirmation setting where you can see connected PSNID(s) and RPCN to your account. To confirm you should write the ID that you want to connect and then the server expects the same IP to connect with that ID. So you would login on the game with the ID and platform chosen, and it would be connected to your account. And then you wouldn't have confirm again. So now when PSNID Example1 connects, it would connect as the Lighthouse account Example3.

This would be very helpful and less complicated atleast for players with constantly changing IPs, if this would be possible

**Comment by jvyden** [comment]
Unfortunately this isn't possible due to how Lighthouse in general and how the game works. Even if it was, it would be pretty high effort. Sorry, just use the same RPCN as your PSN.
