### ISSUE TITLE
The total levels counter displays all uploaded levels as opposed to only Vita levels on LBP Vita

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#208]
The "total" parameter in categories such as "Cool Levels", "Newest Levels", "Highest Rated", "Most Hearted", "Most Played", "Team Picks" and "Lucky Dip" as well as planetStats display the total amount of uploaded levels as opposed to only Vita levels on LBP Vita and vice versa on the main games.
![image](https://user-images.githubusercontent.com/51852312/156056083-fa2e3fd2-366b-43d4-996c-439d0d69283b.png)

**Comment by Slendy** [comment]
Can you confirm if this was fixed in eb7cda8997634b1cf913ebe9f3a7ea2321e8a945?

**Comment by turecross321** [comment]
appears to be fixed yep 
![image](https://user-images.githubusercontent.com/51852312/190854501-7b46491f-0dba-4935-bb1a-86dd3510b7c6.png)

but a new problem seems to have emerged where the total parameter in the queued levels list is stuck at 1
![image](https://user-images.githubusercontent.com/51852312/190854554-a5935ce4-4843-48cb-9b92-7e97ff5885b3.png)

**Comment by Slendy** [comment]
Oh yeah, I forgot to ask did this commit fix it? 40d75626604c19276a88339c0cecfea6614e5ab0

**Comment by turecross321** [comment]
yep! that fixed it, but i've come to realize, (and maybe this should be its own separate issue), the queued levels as well as the hearted levels tab seem to be incredibly broken, on at least LBP Vita. I recorded a video to show what I mean. 

These used to work perfectly fine, and I'm not entirely sure when these issues came to be.

https://user-images.githubusercontent.com/51852312/192057549-621a4e2f-14b0-4a79-951e-78f3e60f4738.mp4

**Comment by TorutheRedFox** [comment]
seems to be a Vita issue as it doesn't occur on PS3 from my experience

**Comment by turecross321** [comment]
closing this in favor of #514
