### ISSUE TITLE
Implement the "Recently Played" and "Busiest" categories

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#209]

**Comment by Arcadius2006** [comment]
turecross how are we gonna get "Busiest" if the server doesn't even check who is playing the level

speaking of which

**Comment by turecross321** [comment]
by implementing it

**Comment by jvyden** [comment]
Not sure how busiest is going to be implemented, since that information isn't stored in the database. That's going to have some very slow queries.

**Comment by jvyden** [comment]
Nevermind, I just needed to think for 5 seconds. I can probably achieve this by looking at the active rooms, storing the counts of how many times a particular slot shows up, and query accordingly.

**Comment by jvyden** [comment]
Busiest tab is implemented in https://github.com/LBPUnion/ProjectLighthouse/commit/d810a3a9f14d2f2e3d9d00fd3a95186def4f0151.
