### ISSUE TITLE
Log in with e-mail as opposed to username?

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#220]

**Comment by m88youngling** [comment]
My comment isn't all that necessary here, but I can imagine this would be helpful to do this because it would make it a little harder for a user to crack into somebody's account if they need to know their email address.

**Comment by TorutheRedFox** [comment]
Minecraft also did this before switching to Mojang (and later Microsoft) accounts btw
![image](https://user-images.githubusercontent.com/15708278/191060207-da925007-9c88-4b59-9f35-9c718e71b4b6.png)
