### ISSUE TITLE
Users cannot "yay" their own comments

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#223]
![image](https://user-images.githubusercontent.com/51852312/157126115-88a02cb5-e4a8-4b22-9db1-a17825669cb1.png)

**Comment by jvyden** [comment]
This is intentional.

**Comment by turecross321** [comment]
I can't see why that's a thing considering there's a button for it?

**Comment by Slendy** [comment]
In every other game you can't rate your own comments or reviews.

**Comment by turecross321** [comment]
![image](https://user-images.githubusercontent.com/51852312/157186784-297fc268-135e-46f1-a80c-c89bdc11670d.png)
Vita's got it

**Comment by jvyden** [comment]
The main target to hit compatibility-wise is LBP2, so oddities such as this one with the Vita edition are probably just going to get ignored. Sorry.
