### ISSUE TITLE
Modifying a slot in any way will reset its gameVersion

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#238]
When moving a LBP1 level on LBP2 for instance, the level will display as a LBP2 level after being moved.

**Comment by jvyden** [comment]
This is somewhat on purpose.

Moving a level counts as a republish, and by default on a republish the gameVersion will be updated to the republisher's current version to avoid LBP2 levels showing up on LBP1 for example.

I can probably check to see if the slot's rootLevel is the same and if it isn't, *then* update the gameVersion.
