### ISSUE TITLE
Add the ability to delete comments on website

### ISSUE THREAD

**Issue by Leafar70** [LBPUnion/ProjectLighthouse#239]
A good enhacement in the website, if it can be made, would be adding the ability to delete:

1. Comments the user makes on their profile
2. Comments other users make on your profile
3. Comments the user makes on levels
4. Comments other users make in your levels.

**Comment by FridiNaTor1** [comment]
And admins/moderators should be able to delete any comment

**Comment by Leafar70** [comment]
thats true.
