### ISSUE TITLE
Show newly team picked and trending levels on the home page of the website

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#241]
![image](https://user-images.githubusercontent.com/51852312/158020874-8a917904-6eea-4432-9826-a3e01da24f29.png)

**Comment by jvyden** [comment]
What exactly does "trending" mean here? :thinking:

**Comment by jvyden** [comment]
The above commit is a rough pass of this feature.

**Comment by jvyden** [comment]
Here's what it looks like:

![image](https://user-images.githubusercontent.com/40577357/161452887-fb62b596-8cd0-4c58-b6f4-85de6c547f4c.png)

Thoughts?

**Comment by turecross321** [comment]
Looks good!

**Comment by Ezoiar** [comment]
Looks nice.

**Comment by jvyden** [comment]
Implemented in b3b5354c68ecd830ba12ad66c669cc62c8a84b7a.
