### ISSUE TITLE
Remove level searching and user searching on website in favor of a combined one

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#242]
I believe it would be cleaner to only use one search bar (as opposed to the 2 seperate search bars for users and levels right now) and maybe include some sort of filtering system instead.

**Comment by Arcadius2006** [comment]
that sounds confusing, i'd rather keep them seperated

**Comment by jvyden** [comment]
Yeah, sounds like a disaster code-wise, too.
