### ISSUE TITLE
PS Vita browser not detected as mobile browser

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#243]
The lighthouse website does not display correctly on a PSvita, perhaps using the mobile ui would help?

**Comment by jvyden** [comment]
Can you tell me the useragent of the PS Vita browser?

**Comment by FridiNaTor1** [comment]
> Can you tell me the useragent of the PS Vita browser?

![20220319_202010](https://user-images.githubusercontent.com/32988388/159137193-61a7e983-617d-44cc-8aee-21914abc77e6.jpg)
I took a picture of it

**Comment by jvyden** [comment]
`Mozilla/5.0 (PlayStation Vita 3.73) AppleWebKit/537.73 (KHTML, like Gecko) Silk/3.2
