### ISSUE TITLE
Block the ability to upload photos if the photo-taken-date is in the future

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#259]
Right now you can change the date/time on your console to the future (2023 for instance), take a photo, and since the website sorts photos by the date that the photo was taken, you can essentially pin photos on the website.
![image](https://user-images.githubusercontent.com/51852312/161375674-0769feb2-0823-42c2-8e2a-dfe42f94296f.png)

**Comment by jvyden** [comment]
Resolved in 02fa66b.
