### ISSUE TITLE
Website does not display the level limit correctly

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#260]
If the upload level limit is 50, every user can upload 50 main lbp levels and 50 Vita levels, but the website doesn't show this correctly.
![image](https://user-images.githubusercontent.com/51852312/161375802-42a8bcae-c036-4a2f-bcda-cc4110637a7a.png)

**Comment by jvyden** [comment]
Probably just going to resolve this by removing the max count entirely, since it's variable depending on what games you play.
