### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by Ezoiar** [LBPUnion/ProjectLighthouse#268]
The title is self-explanatory, Basically a selection of languages if the user does not understand English. This can probably be done by making localization files for each language, and users who wants to volunteer on localizing. For example, Me, I can probably do Danish. and I have a few more friends worldwide that can probably do some other languages. OH YEAH NEVER USE GOOGLE TRANSLATE, ITS INACCURATE.

I recommend using flags as well, It's to make selecting a language easier. I can probably help with flags since I learnt too much on flags.
You can get flags here which I feel best fit. http://www.famfamfam.com/lab/icons/flags/

![How it would look like.](https://user-images.githubusercontent.com/36406820/162293809-c6f06c97-3f22-4bc4-a433-a2ec5411fa92.png)

**Comment by Arcadius2006** [comment]
could i help with the polish translation?

**Comment by Ezoiar** [comment]
Go ahead.
I will do Danish and I have a few friends and family who can do Japanese, Simplified Chinese, Filipino, and German.

**Comment by Arcadius2006** [comment]
all i really need to get is the text strings lighthouse uses

**Comment by jvyden** [comment]
By the way, this is being worked on by me on my local branch: https://github.com/jvyden/ProjectLighthouse/tree/crowdin

**Comment by jvyden** [comment]
There's also a crowdin project here: https://crowdin.com/project/project-lighthouse
