### ISSUE TITLE
using the announcements screen to make custom error messages

### ISSUE THREAD

**Issue by Toastbrot236** [LBPUnion/ProjectLighthouse#289]
Maybe make it so if someone tries to connect to the server and fails, before giving them a 403, give them an announcement screen that explains what the issue is (no account, no approved authentication etc).

**Comment by jvyden** [comment]
We tried this in our initial implementation of external authentication, and unfortunately it caused more problems than it solved. Unfortunately, the way it is now is just gonna have to be how it works. 

We might add some sort of website-side "sidekick" area where you can view more details about recent actions you did in-game which *might* help with this issue, but that's way in the future.

Thus, I'm closing this issue.
