### ISSUE TITLE
taking a picture with the snapshot button in the start menu and then uploading it will mess the player coordinates up

### ISSUE THREAD

**Issue by Toastbrot236** [LBPUnion/ProjectLighthouse#291]
![Screenshot 2022-04-23 23-16-43](https://user-images.githubusercontent.com/95178340/164946224-1407a013-741a-4ec2-8223-0d33cd199e5d.png)
![Screenshot 2022-04-22 23-01-51](https://user-images.githubusercontent.com/95178340/164946225-aaf30cee-e51b-4279-acac-d35bd20b198f.png)

**Comment by turecross321** [comment]
I do not believe there is much to do about this because I am fairly certain this is an LBP bug, as opposed to a Lighthouse bug.

**Comment by jvyden** [comment]
Yeah, not much to be done about this. Sorry.
