### ISSUE TITLE
Implement Filters in the Levels Tab (on the website)

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#298]
It should be possible to filter the level results on the website. (The filter I'm mainly thinking of is filtering out specific LBP games like Vita for instance, but other filters like only showing specific tags would also be cool)

**Comment by Ezoiar** [comment]
this issue already exists i think lol

**Comment by turecross321** [comment]
Oh, yeah, you're right. My bad.
