### ISSUE TITLE
Disable autocomplete on search forms

### ISSUE THREAD

**Issue by Slendy** [LBPUnion/ProjectLighthouse#309]
On inputs like level search, the browser shouldn't try and autocomplete. 

![image](https://user-images.githubusercontent.com/16675503/168447258-5de8c95c-e0d8-40bb-bbfc-660e6a56bb60.png)

**Comment by Toastbrot236** [comment]
why tho

**Comment by Slendy** [comment]
So the browser doesn't try and do this
![image](https://user-images.githubusercontent.com/16675503/172079122-9329d162-d7bc-41b3-beef-a57030403bf2.png)
it's just a minor QOL thing

**Comment by Toastbrot236** [comment]
could be very useful tho (useful as in, i use it a lot)

**Comment by turecross321** [comment]
The built-in web browser history looks really bad but I think a history tied to the lighthouse account could still be nice.
