### ISSUE TITLE
Round LBP1 star rating on website

### ISSUE THREAD

**Issue by Slendy** [LBPUnion/ProjectLighthouse#331]
floating point go brr
![image](https://user-images.githubusercontent.com/16675503/175356664-aa33a9bf-8405-42d1-bc08-c03384047c9e.png)
![image](https://user-images.githubusercontent.com/16675503/175356977-c4dd8039-0c83-4580-aa80-bd32a5377822.png)

**Comment by Toastbrot236** [comment]
smells like mod abuse...

**Comment by Salamni** [comment]
what

**Comment by TorutheRedFox** [comment]
round it to the nearest .5 I guess? (or maybe floor it idk)
