### ISSUE TITLE
Login tokens never expire

### ISSUE THREAD

**Issue by Zaprit** [LBPUnion/ProjectLighthouse#335]
When a web login is done it stores a token on the users machine with an expiry date of 7 days, however the token that goes into the database is not checked and in fact has no timestamp, this stands out to me as a security vulnerability.

**Comment by jvyden** [comment]
`GameToken`s should also be wiped once the user is deemed offline, but that might be very expensive to check for.

**Comment by TorutheRedFox** [comment]
an easier way to check whether a token is expired or not is to simply check when a request is made using it, and occasionally do a purge of all entries in the database that are older than 7 days to save space
