### ISSUE TITLE
Add censorship to POST /filter 

### ISSUE THREAD

**Issue by jvyden** [LBPUnion/ProjectLighthouse#34]
The community can be harmed by dangerous words like "toyo". Censoring words like that can help improve the servers.

*/s*

**Comment by alkalinethunder** [comment]
I approve

**Comment by Ezoiar** [comment]
I agree

**Comment by ToruTheRedFox** [comment]
yeah, "computer" is a very dangerous word

**Comment by Arcadius2006** [comment]
add customizability to what words are censored possibly
