### ISSUE TITLE
Dive-in issues....

### ISSUE THREAD

**Issue by Salamni** [LBPUnion/ProjectLighthouse#341]
Dive-in has been broken ever since the implementation of universal user count across games. 3 outcomes; 1. Almost guaranteed/immediate "Failed to connect to players" even with numerous users on the same game as you. 2. "We couldn't find anyone for you to join. Waiting for players to join you..." Again, Immediately upon trying to dive in. And the befabled 3. It asks someone if you can join, then either immediately or after a second or two, it'll say "Failed to get responses from players we wanted to join." then immediate "Failed to connect to players". Do fix asap.

**Comment by Salamni** [comment]
Side note, this issue occurs even when all the users are on the same game as you

**Comment by Salamni** [comment]
bruh

**Comment by Zaprit** [comment]
> bruh

Bruh, you need to be patient, the person who does the main LBP API stuff in on leave. all of these issues will get sorted, just not now

**Comment by jvyden** [comment]
Pretty sure this is related to #347

**Comment by jvyden** [comment]
Fixed in c231af0.
