### ISSUE TITLE
Good Grief Report Discord Integration 

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#352]
![image](https://user-images.githubusercontent.com/51852312/179353492-f93865a9-7f79-4f65-898c-10f3fc0755af.png)
Something like this, but instead that shows reports when they come in would help moderators get notified when reports are made more easily.

**Comment by jvyden** [comment]
@m88youngling What channel in the discord should I add this to? #star-command?

**Comment by m88youngling** [comment]
> 

1000537682348355674 use that channel ID, it's a new channel called beacon-grief. Peacekeepers, Starblazers, and devs have access

**Comment by jvyden** [comment]
Closed in 6ca81e042
