### ISSUE TITLE
Verification Mail lacking a page

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#357]
Currently you get a 500 error when Lighthouse sends you a verification mail, and while it works, I've seen many people find it confusing. I think a specific page that tells you that a mail has been sent would help to clear up confusion.
![image](https://user-images.githubusercontent.com/51852312/179375545-a8ba995b-17ae-4a20-9af1-eab38fc00f90.png)

**Comment by Zaprit** [comment]
I can't reproduce this, was this on a local build and if so, was it a debug build or a release build

**Comment by turecross321** [comment]
> I can't reproduce this, was this on a local build and if so, was it a debug build or a release build

 Official instance

**Comment by Zaprit** [comment]
huh, if i go there it just redirects me to login, and if i try while logged in it just redirects me to the home page

**Comment by turecross321** [comment]
try making a new account, and adding an email.

**Comment by turecross321** [comment]
https://user-images.githubusercontent.com/51852312/179395548-25f599cf-1699-43cf-a185-82d5cefece35.mp4

**Comment by Zaprit** [comment]
that looks like what would happen if the email server was down.
