### ISSUE TITLE
Update compatibility list

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#362]
RPCS3 master branch can now connect to LBP servers just fine, making the patch requirement outdated as it's no longer required.

It does seem to be a tad bit unstable though.

**Comment by Zaprit** [comment]
In regards to this, can someone please test LBP3 on the latest build of RPCS3 to see if it still crashes a lot

**Comment by jvyden** [comment]
> In regards to this, can someone please test LBP3 on the latest build of RPCS3 to see if it still crashes a lot

From experience since writing that it ended up being not just an RPCS3 issue, it happens on real hardware too. LBP3 PS3 is just buggy. /shrug

I'll update it at some point, or someone can open an MR.
