### ISSUE TITLE
lbpEnvVer too long

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#363]
The server name is sent along with the rest of the auth stuff in the LITTLEBIGPLANETPS3_XML/login response in the lbpEnvVer tag.
The exclusion of this makes the server show up as unknown in LBP2 br2_r47518 and other mspf enabled builds.

**Comment by TorutheRedFox** [comment]
pretty sure it's lbpEnvVer anyways

**Comment by TorutheRedFox** [comment]
![image](https://user-images.githubusercontent.com/15708278/180458474-1b177571-79f6-4989-9ae4-d23b2928ad98.png)

**Comment by TorutheRedFox** [comment]
looks like it is but it's bugged? odd?

**Comment by Slendy** [comment]
The field has a max character limit, and since Lighthouse sends a very long string for version the game just ignores it. The solution is to either use a shorter version string or truncate the string if it gets too long.

**Comment by TorutheRedFox** [comment]
huh

**Comment by TorutheRedFox** [comment]
maybe having the envver sent to the game be separate from the one displayed on the site would be good?

**Comment by TorutheRedFox** [comment]
I have an implementation I use for private testing here: https://github.com/TorutheRedFox/ProjectLighthouse

**Comment by TorutheRedFox** [comment]
i.e. branch that isn't both clean and called "main"
![image](https://user-images.githubusercontent.com/15708278/180609545-4e2d1272-b8da-4475-9422-701baac4ddb4.png)
branch that is both clean and called "main"
![image](https://user-images.githubusercontent.com/15708278/180609600-bb464be8-a348-46e3-9592-840432a0e71e.png)

'lbp2-server-new' is just the server name defined in the config

**Comment by jvyden** [comment]
Personally not a fan of the revision count as opposed to revision hash due to both conventions and concerns about shallow cloning. 

I wouldn't be against a format like `{serverName} {gitBranch} {gitHash}` though.

It's also important to note that this isn't really used anywhere except for an optional display in debug builds, so this is pretty low priority.

**Comment by TorutheRedFox** [comment]
I'm using revision count because I find it more human readable

also it's easier to check when used in a game
