### ISSUE TITLE
LBP2 levels counted towards level total in LBP1

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#365]
Here I have 2 LBP1 levels published and 3 LBP2 levels published, yet in LBP1, the LBP2 levels count towards the total when they technically shouldn't
![image](https://user-images.githubusercontent.com/15708278/180611576-50e9732f-b314-42fb-a625-e3c14061a56b.png)

**Comment by jvyden** [comment]
This is intentional.

**Comment by TorutheRedFox** [comment]
oh ok
