### ISSUE TITLE
LBP2 current player counter malfunction

### ISSUE THREAD

**Issue by Sonemy** [LBPUnion/ProjectLighthouse#366]
I've noticed that one of the LBP2 levels has a current player counter indicating that a user is currently playing the level. This player counter has been visible for several days. I'm certain that there is no player playing this level at this time. 
![](https://cdn.discordapp.com/attachments/895826244963282944/1000526869998878750/20220723_144747.jpg)

**Comment by jvyden** [comment]
Have these disappeared?

**Comment by Sonemy** [comment]
Yes, they are gone now.

**Comment by Sonemy** [comment]
I just noticed that this was very similar to [issue 347](https://github.com/LBPUnion/ProjectLighthouse/issues/347) which occurred on Vita.

**Comment by jvyden** [comment]
Probably a duplicate then; closing in favor of #347.
