### ISSUE TITLE
Uploaded photos get shown on all level InfoBubbles

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#378]

**Comment by TorutheRedFox** [comment]
![BCET70023_screenshot_2022_07_28_16_05_16](https://user-images.githubusercontent.com/15708278/181572032-a569f580-34fb-4aa4-bcb9-ec991c21c358.png)

**Comment by TorutheRedFox** [comment]
nevermind it's on all uploaded photos
![BCET70023_screenshot_2022_07_28_16_09_28](https://user-images.githubusercontent.com/15708278/181573036-a03bf47a-7390-4b34-b1bc-39b0cf1be49f.png)

also photos button is grayed out on levels

**Comment by jvyden** [comment]
Duplicate of #144
