### ISSUE TITLE
Implement recently played section

### ISSUE THREAD

**Issue by Slendy** [LBPUnion/ProjectLighthouse#379]
The game seems to store user-created and story levels that were played and request metadata about them. The response should contain a list of serialized slots that match the ids that were given.

Example request:
`GET /LITTLEBIGPLANETPS3_XML/slotList?s=7&s=124872&s=124873&s=3584&s=3970&s=3998&s=4205&s=3356&s=3363&s=3511&s=3777&s=4010&s=4101&s=4104&s=4156&s=3322&s=3433&s=3973&s=3434&s=3805&s=3
552&s=3873&s=3942&s=3409&s=124814&s=124808&s=124824&s=124813&s=3194&s=3077`

Example structure of a response:
```
<slots count="3">
  <slot type="user">
    <id>5</id>
  </slot>
  <slot type="developer">
    <id>124872</id>
  </slot>
  <slot type="user">
    <id>43</id>
  </slot>
</slots>
```

**Comment by TorutheRedFox** [comment]
partially related to #367
