### ISSUE TITLE
Customization of EULA layout

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#380]
The agpl license always comes first. I feel that the owner should be able to position it (but not remove it) a little further down to get some important points about rules and stuff out of the way, as most people would probably just read half of the agpl license and click accept.

Maybe do it with rext replacement like with announce, and if the %license text is not there, then throw a warning in console that exluding the license is not allowed and prepend it?

**Comment by jvyden** [comment]
That's on the user for not reading important information :p

We'll have a place on the website for instance rules in the future, which will probably work way better for everyone. For now, the way it works now is fine.

**Comment by TorutheRedFox** [comment]
ok
