### ISSUE TITLE
Play counts broken on LBP3

### ISSUE THREAD

**Issue by W0lf4llo** [LBPUnion/ProjectLighthouse#404]
As see in these images the play counts for levels shown on LBP3 is broken. This is not a very big issue but I’m sure it could be resolved fairly easily (not sure since I’m not a dev) if this is resolved thank you as it’s mildly annoying when I’m looking at my plays and they don’t show up. Then I’d have to go to LBP2 or the website in order to view the player counts. Thanks for reading and have a fantastic day 😄![image](https://user-images.githubusercontent.com/96880844/183236716-30ac4e97-9a5e-446b-bbd0-f7c78c651f6d.jpg)
![D4C9AA79-2957-49D3-A680-F5AC41580608](https://user-images.githubusercontent.com/96880844/183236731-27b66070-eaec-4b30-9eae-188b111759ca.jpeg)

**Comment by jvyden** [comment]
Oh, I didn't realize what this was until now. This is a quirk of LBP3; it uses the amount of plays for LBP3 only. Not much we can do about this, unfortunately.
