### ISSUE TITLE
405, 8ms: GET /LITTLEBIGPLANETPS3_XML/scoreboard/user/20 in LBP1

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#411]
GET for /scoreboard/user/{userId} doesn't seem to be supported oddly enough

**Comment by Slendy** [comment]
Does it use this endpoint for submitting scores or viewing scores?

**Comment by TorutheRedFox** [comment]
viewing scores seemingly as it sent that request when I was in the Pod

**Comment by TorutheRedFox** [comment]
thinking about it, it can't send a score if it's a GET request
