### ISSUE TITLE
player count on dive in button is always zero in early versions of LBP2

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#417]
![BCET70023_screenshot_2022_08_09_18_13_27](https://user-images.githubusercontent.com/15708278/183715019-3e145169-19a7-4166-bf76-3eeb2708fb84.png)

**Comment by jvyden** [comment]
This is intentional as part of how the old dive-in system worked. It's counting the amount of people in levels; not how many are globally online.

**Comment by TorutheRedFox** [comment]
on a side note, dive in also doesn't seem to work?

like, a player may be in a level, but it can't find them
