### ISSUE TITLE
Disable crowdin sync on forks to prevent notification spam

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#432]
there isn't really a label for issues with the repo setup itself so ignore the label

![image](https://user-images.githubusercontent.com/15708278/184554803-f4b4d6b4-2fe0-4808-8883-72ff6b9d6fb0.png)

**Comment by jvyden** [comment]
In the future you can open a blank issue:

![image](https://user-images.githubusercontent.com/40577357/184554908-d4b02612-2bdb-406e-b2f4-0bcb2a97adc4.png)

**Comment by TorutheRedFox** [comment]
oh xd
