### ISSUE TITLE
LBP2 levels not loading or able to be played

### ISSUE THREAD

**Issue by amsash** [LBPUnion/ProjectLighthouse#434]
**Describe the bug**
this is a bug present within levels built in LBP2 that don't allow some people to play any levels at all, when trying to load into these levels and play them it just errors out with a "failed to load level" popup

**To Reproduce**
1. Go to the community tab on the LBP2 pod computer
2. Find any level you want to play
3. Try and load into it
4. level exits out and a popup reading "failed to load level" shows up

**Expected behavior**
when trying to play a level, it is usually expected that you are able to load into it and play it fully, but this does not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/34011884/184656224-9becd8fd-1eb2-4976-874a-5417660016d6.png)
![image](https://user-images.githubusercontent.com/34011884/184656253-90e16837-b343-4ce6-9ae7-0223185cacc9.png)

**Game(s) affected**
 - The platform i am playing on is RPCS3 
 - I am playing on LBP2 although i have not tested whether this issue persists in LBP3
 
**Additional context**
I know that this issue only happens for a select few players trying to play the game, as most people are able to safely and reliably play any level with no issues, while a small amount of people (including myself) aren't able to play any level made within LBP2 at all, which is quite annoying,
i also think this issue has something to do with the levels themselves, and not the actual game, since i can search up levels made in LBP1 and load into them in LBP2 perfectly fine and play them completely, so it is likely something to do with the levels
one last thing i know is that whenever this happens these errors show up in the console
`E sys_net: Socket error ETIMEDOUT`
`E SYS: 'sys_net_bnet_connect' failed with 0xffffffc4 : -SYS_NET_ETIMEDOUT`
i do not understand myself what they would entail though.

**Comment by TorutheRedFox** [comment]
it's up to the instance host to also provide resn (where n is a hexadecimal number 0 through f) subdomains as late LBP2 and LBP3 load resources through them

if it doesn't exist or has issues, they won't be able to load anything, no decorations, no photos, no levels, etc.

**Comment by Slendy** [comment]
Closing as not able to be reproduced. Most likely your game was not updated to the latest version.
