### ISSUE TITLE
LBP3 Servers not working

### ISSUE THREAD

**Issue by W0lf4llo** [LBPUnion/ProjectLighthouse#435]
**Describe the bug**
LittleBigPlanet 3’s game servers seem to be unresponsive for the time being

**To Reproduce**
There are no steps to reproduce this error. LittleBigPlanet 3 seems to be the only game that’s being affected currently. It lets you connect to the servers but it doesn’t load your earth, moon, levels, or anything online related. Community tab doesn’t work, searching doesn’t work, etc.

**Expected behavior**
I expected the game to work so I could publish some of my levels backups and play them with Friends, but as soon as I got to my pod nothing loaded at all.

**Screenshots**
Sadly didn’t take any since I don’t want the game to crash lol.

**Game(s) affected**
 - Platform PlayStation 3
 - Game LittleBigPlanet 3

**Additional context**
If you fix this issue you’re goated.

**Comment by jvyden** [comment]
This was a prod issue; `gzip` was interfering with LBP3

**Comment by TorutheRedFox** [comment]
huh
