### ISSUE TITLE
LBP1 comments do not work

### ISSUE THREAD

**Issue by Le00nn** [LBPUnion/ProjectLighthouse#446]
**Describe the bug**
The comments sometimes will not load at all for any community levels in LittleBigPlanet 1 while they show up on website.

**To Reproduce**
1. Go to 'community'
2. Scroll over to 'comments' section
3. No comments will show

**Expected behavior**
Comments should always show up in game if there are any for said level, not just website only.

**Game(s) affected**
 - Platform RPCS3 (unsure if it's an issue for PS3 too?)
 - Game LBP1

**Comment by Slendy** [comment]
This is unfortunately just a limitation of lbp1, the game doesn't initially request the comment list. In my testing, if you hit the refresh button the comments should show up within a minute or so.
