### ISSUE TITLE
Cannot delete other people's photos on your level.

### ISSUE THREAD

**Issue by Ezoiar** [LBPUnion/ProjectLighthouse#448]
**Describe the bug**
The bug is that you cannot delete photos that aren't yours in your own levels even if the game gives you the choice to do it.

**To Reproduce**
1. Go to any of your own levels that has photos that aren't yours,
2. Go to the level's photos
3. Go to any image that isn't yours.
4. Attempt to delete it.
5. See error

**Expected behavior**
If you delete the photo, The game should delete it.

**Screenshots**

**Game(s) affected**
 - Platform: PS3, and most likely RPCS3. Unsure if Vita works.
 - Game: LBP2, Unsure if other games work.

**Comment by Slendy** [comment]
Closed in fddef506c82862962aa544f9220e690182c3617f
