### ISSUE TITLE
LittleBigPlanet 3 Crashes on PS3 Upon Connecting to Lighthouse

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#453]
**Describe the bug**
Connecting LittleBigPlanet 3 to Lighthouse and continuing past the announcement screen results in a crash. 

**To Reproduce**
1. Boot LBP3 and connect to PlayStation Network.
2. Attempt to connect to online features (results in a 403, as expected). 
3. Approve your authentication attempt. 
4. Attempt to connect to online features again. 
5. The announcement screen will appear. Confirm to continue. 
6. The game crashes. 

**Expected behavior**
The expected behavior is well...the game shouldn't crash. 

**Screenshots**
N/A

**Game(s) affected**
 - PlayStation 3 
 - LittleBigPlanet 3 

**Additional context**
We were able to get LBP3 working recently on Beacon with Cloudflare protection by changing a configuration in nginx to allow http.

**Comment by TorutheRedFox** [comment]
that doesn't really sound like an issue with Lighthouse itself but with any http reverse proxies that may be in between the client (LBP3) and the server (Lighthouse)

**Comment by m88youngling** [comment]
> that doesn't really sound like an issue with Lighthouse itself but with any http reverse proxies that may be in between the client (LBP3) and the server (Lighthouse)

Hopefully we will find a solution, whether it's Lighthouse related or not. Someone from our team recently got a bunch of packet captures from successful and failed LBP3 connect attempts. Soon I'd like to get those posted here when we can so contributors can take a look

**Comment by Slendy** [comment]
Fixed in b1ad4d3218f2a69cad81b6a92cf45ae32341736e.
