### ISSUE TITLE
Banned user still able to login and browse the community in-game

### ISSUE THREAD

**Issue by Ezoiar** [LBPUnion/ProjectLighthouse#461]
**Describe the bug**
The title speaks for itself.

**To Reproduce**
1. Ban an account.
1.5. Try to see if automated IP authentication and manual IP authentication does anything.
2. Attempt to log in with that account in-game.
3. Go to community.

**Expected behavior**
The banned account should receive an error and fail to login. 

**Additional context**
It was found by an EX-USC scout who somehow logged in after being banned (by request)

**Comment by m88youngling** [comment]
Are you sure the case hasn't just expired? Or, is this an issue of case expiration not working as expected?

**Comment by Ezoiar** [comment]
It wasn't expired at all.

**Comment by TorutheRedFox** [comment]
this kinda gives me an idea

a kind of suspension that behaves like this intentionally, where you can log in, browse and play levels, etc., but you can't upload anything (basically a suspension on uploading files, e.g. due to file upload spam from that user)

**Comment by m88youngling** [comment]
Ah yeah, I do believe we have a shadow ban feature, and if not it was discussed. Probably should codename the feature '1984' or something lmao

**Comment by Ezoiar** [comment]
nice name :troll:

**Comment by Slendy** [comment]
This was a bug caused by a LevelHide case that had an associated id that didn't exist. Since there was no error handling in the case processing function it wouldn't process the rest of the cases which included the ban. I fixed the issue in 22905d419c503b35b2aefaf55dc3ff0da98363c9 and the ban case processed correctly now.
