### ISSUE TITLE
LBP3 1.26 not loading resources from server

### ISSUE THREAD

**Issue by LBPHaxMods** [LBPUnion/ProjectLighthouse#482]
**Describe the bug**
Resources from the server will fail to load. 

**To Reproduce**
1. Connect to server
2. Go to profile or level
3. Photos will not load. Levels and planet decorations also kick you back to pod.

**Expected behavior**
Photos and levels should load correctly, instead of the error icon or kicking back to pod.

**Screenshots**

How it should look (Using LBP3 1.13, which does not require HTTPS)
![Screenshot 2022-09-18 230001](https://user-images.githubusercontent.com/92583355/190949820-56725c0e-b995-4c8d-bdac-c51306cc1cab.png)

How photos taken in other games and LBP3 versions show in 1.26 (photos taken in 1.26 show up as they normally would)
![Screenshot 2022-09-18 231307](https://user-images.githubusercontent.com/92583355/190949884-feb7d0e6-354e-4362-ae14-00fd47a8947e.png)

Levels and planet decorations failing to load, loading times trimmed.

https://user-images.githubusercontent.com/92583355/190949924-0a10d3af-ffaa-4d0c-ae6b-973be25fe44d.mp4

**Game(s) affected**
 - Platform [RPCS3, but likely PS3 as well.]
 - Game [LBP3 1.26]

**Comment by LBPHaxMods** [comment]
Replying to this as this still happens for me on Beacon
![image](https://user-images.githubusercontent.com/92583355/223287803-a54e37d7-2a90-4b38-9564-e7a8d3ff9826.png)

**Comment by LBPHaxMods** [comment]
I just realized that I was somewhat incorrect here, it just doesn't load any hashed content at all, even if uploaded from 1.26, I've tried using a fresh eboot but it still doesn't work, no idea why.

**Comment by LBPHaxMods** [comment]
I was messing around and it seems like in some cases it will load a few assets, but not the rest. (like how the level icon loaded here, but not the user icon)
![image](https://user-images.githubusercontent.com/92583355/224463391-c597bc07-8e28-406d-b919-df419c97436c.png)

**Comment by TorutheRedFox** [comment]
afaik this is caused by res0.lbpunion.com through resf.lbpunion.com (format is res_.lbpunion.com where _ is a hexadecimal number) not existing

it's entirely a beacon setup issue and not an issue with lighthouse itself (it affects later versions of LBP2 too)

**Comment by sudokoko** [comment]
> afaik this is caused by res0.lbpunion.com through resf.lbpunion.com (format is res_.lbpunion.com where _ is a hexadecimal number) not existing
> 
> it's entirely a beacon setup issue and not an issue with lighthouse itself (it affects later versions of LBP2 too)

I can confirm that these res domains exist. Feel free to open a CrashHelper report at https://crashhelper.lbpunion.com if you're experiencing a Beacon-specific issue.

**Comment by LBPHaxMods** [comment]
okay so it turns out the issue was i had my game patched to beacon.lbpunion.com, and not lighthouse.lbpunion.com 
![image](https://user-images.githubusercontent.com/92583355/226076952-202004c9-5b9f-499c-b129-d5f14a77b584.png)
