### ISSUE TITLE
Changing level metadata in different game changes its game version

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#486]
Say you were to upload a level in LBP1 and go to change metadata in LBP3 (i.e. add a tag), the level would now be considered to be an LBP3 level and no longer show up in LBP1 or 2.

**Comment by Slendy** [comment]
This is an intended feature. To make the level update to the new version you have to edit the level and change something then save and republish.

**Comment by TorutheRedFox** [comment]
problem is that this makes the LBP1 only flag useless as you can only set it from LBP2, which in turn makes it an LBP2 level

**Comment by Slendy** [comment]
I think I misunderstood your report. What I meant to say is that the version of a level should not change unless the rootLevel changes aka you edit the level in create mode and save changes. Can you give more details like did you edit the labels by copying the level to your moon and then republishing or did you edit them directly from your earth?

**Comment by TorutheRedFox** [comment]
I edited them directly from my earth in LBP3 prebeta

I don't think the fact it's prebeta has anything to do with it though (as rootlevel hasn't changed and manually switching the gamever back in the db to 0 made it work in older games again)

**Comment by TorutheRedFox** [comment]
specifically I added tags to the level because I forgot to add them before

**Comment by Slendy** [comment]
I can confirm that this is an LBP3-related issue. The game actually uploads a new rootLevel file with an lbp3 version even if you change something on the earth like the labels, description, locked, copyable, or sublevel options. If you try to do the same thing in LBP2 it works as expected.

**Comment by TorutheRedFox** [comment]
weird

**Comment by Slendy** [comment]
Thankfully it should be possible to protect LBP3 from itself because it sends a game query parameter in the publish request so you can determine if it's trying to forcefully update the level.

**Comment by TorutheRedFox** [comment]
thinking about it as a sidenote

this bug seems to have been present on the official servers too, but it didn't actually update the gameversion, so you were just left with a level that'd only load in lbp3 but would show up in lbp1 and lbp2 (one such level that comes to mind is an upload of the pod level by i think fattymcintosh)
