### ISSUE TITLE
“Filters” tab not working in LBP3

### ISSUE THREAD

**Issue by W0lf4llo** [LBPUnion/ProjectLighthouse#488]
**Describe the bug**
The “Filters” tab is unimplemented in LBP3. When you try to access it all the options show up but the tags don’t filter out, the game selected doesn’t filter out, nothing in there works. I would really like this to be implemented but I think “Playlists” should be worked on first as it’s an option inside of the filters tab. It could be worked on the side and have small features added at a time but for the time being without playlists then full filters tab won’t be complete.

**To Reproduce**
1. Go to “Community”
2. Click on “Recommended”
3. Choose any tab (Newest Levels preferred)
4. Click on R3 and the “Filters” tab shows up, none of the options work

**Expected behavior**
They should filter out the options from levels, adventures, playlists, and if it has players (I think that’s what it means.) the tags should bring up lbp levels with those tags. And the bottom options should pull up levels from those specific games and if they require a PS Move. (I don’t even think that’s implemented either but I’m unsure).

**Screenshots**
![5BEB66C0-9F3C-435E-B3B8-3ECF2DAB129B](https://user-images.githubusercontent.com/96880844/191655836-ae6bc899-de57-40f0-bb7f-8e085cf799bc.jpeg)
![5C1682EC-F98B-436A-B754-138EFD1F54E7](https://user-images.githubusercontent.com/96880844/191655841-e604432b-41ea-49a1-81ed-a84f6eef6a83.jpeg)
![B125771A-6105-4823-9222-F22EB6D88D36](https://user-images.githubusercontent.com/96880844/191655844-24b495a7-de4b-4a07-afff-7aa8c289ff4d.jpeg)
![CAFCA223-BDD2-4D3A-8480-92B22B9CDDC0](https://user-images.githubusercontent.com/96880844/191655848-5f8498c2-3ad1-4769-8958-d60d3c9c77e2.jpeg)

**Game(s) affected**
 - Platform (Any)
 - Game (LBP3)

**Additional context**
I wish the devs luck on fixing this issue as this might be as hard as “Recent Activity”. Let’s hope we can get lbp3 fully functional someday :)

**Comment by TorutheRedFox** [comment]
it's actually not as hard as recent activity, it's just a bit time consuming to add all of the sorting options to every slot list type

**Comment by Arcadius2006** [comment]
doesn't this actually not work on ALL games? i also remember requesting this problem ages ago

**Comment by Arcadius2006** [comment]
yeah, #90

**Comment by sudokoko** [comment]
This should be closed once/if #597 is finished.

**Comment by daggintosh** [comment]
> This should be closed once/if #597 is finished.

It will be closed in a later commit, this PR will (eventually) implement a basic filter system but only for LBP3 and LBP2/V Recent Activity filters.

I will apologize for the great delay though as I have had next to zero motivation for working on the project unfortunately.

**Comment by m88youngling** [comment]
> I will apologize for the great delay though as I have had next to zero motivation for working on the project unfortunately.

https://youtu.be/ZXsQAXx_ao0

**Comment by daggintosh** [comment]
I'm allergic to YouTube: Broadcast Yourself.

**Comment by sudokoko** [comment]
> > I will apologize for the great delay though as I have had next to zero motivation for working on the project unfortunately.
> 
> https://youtu.be/ZXsQAXx_ao0

Meme... approved!

**Comment by daggintosh** [comment]
> > > I will apologize for the great delay though as I have had next to zero motivation for working on the project unfortunately.
> > 
> > 
> > https://youtu.be/ZXsQAXx_ao0
> 
> Meme... approved!

![MEME... Approved!](https://media.tenor.com/yIWM3TO6ScEAAAAd/meme-approved-knuckles.gif)

**Comment by daggintosh** [comment]
Alright back to (hardly) professional comments. Sorry to the participants for the spam.
