### ISSUE TITLE
LBP3 Dive in won’t find other players.

### ISSUE THREAD

**Issue by W0lf4llo** [LBPUnion/ProjectLighthouse#503]
**Describe the bug**
Dive in in LBP3 works but it won’t find any players to join your game. I tested this with two friends .

**To Reproduce**
1. Boot up LBP3
2. Pause the game and press “Play Online”
3. Select dive in and host a lobby and have a friend try to join you. 
4. It won’t work.

**Expected behavior**
it should find a lobby that’s being hosted and join them.

**Screenshots**
(No need for screenshots as they won’t show the issue).

**Game(s) affected**
 - Platform PS3
 - Game LBP3

**Additional context**
Good luck!!

**Comment by sudokoko** [comment]
Is this and #454 still an issue? Confirmation and any additional details would help.

**Comment by W0lf4llo** [comment]
Same with this one, been fixed
