### ISSUE TITLE
Hearting and Queuing in LBP Vita doesn't work properly

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#514]
**Describe the bug**
The queued and hearted levels lists display levels that you've not actually hearted/queued, and since the levels aren't actually queued/hearted, it's not possible to remove them from the list either.

**To Reproduce**
1. Go to your hearted or queued levels list in LBP Vita.
2. You'll see levels that you've not even hearted/queued in the list.
3. Try to unheart or unqueue one of the levels in the list
4. Everything stays the same

**Expected behavior**

- When you heart a level, it should go to the hearted levels list, and when you queue a level it should go to the queued levels list.
- When you unheart a level, it should disappear from the hearted levels list, and when you unqueue a level it should disappear from the queued levels list.

**Video demonstration**

https://user-images.githubusercontent.com/51852312/195021694-35ddbe62-7a76-49ec-ae7c-4a9e3e2df86e.mp4

**Game(s) affected**
- LBP Vita

**Additional context**
This used to work completely fine, and it works normally on all games other than LBP Vita from what I know. Literally no idea why LBP Vita is the only game affected.

**Comment by turecross321** [comment]
I hate being the guy that does this, but when is the going to be addressed?

**Comment by Slendy** [comment]
I've identified the cause of the issue [here](https://github.com/LBPUnion/ProjectLighthouse/blob/main/ProjectLighthouse.Servers.GameServer/Controllers/Slots/ListController.cs#L341-L344). I'll try to get around to fixing it sometime this week

**Comment by Slendy** [comment]
Can you confirm if this issue is fixed in 9d25f56?

**Comment by turecross321** [comment]
Appears to be fixed!
