### ISSUE TITLE
Cross Controller levels cannot be uploaded

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#53]
The player doesn't have a seperate earth while in Cross Controller mode and cannot upload any kind of level

**Comment by jvyden** [comment]
Can you provide a level backup of the level you're trying to upload?

**Comment by jvyden** [comment]
Er, misinterpreted. What do you mean by "seperate earth"?

**Comment by Arcadius2006** [comment]
the Cross Controller Premium Level Kit provides you with a seperate level list from your usual one, so you can't play regular levels on cross controller or cross controller levels without cross controlller

also im sending the backup rn

**Comment by jvyden** [comment]
@hydronePVP45 can you pull the names of the endpoints for this?

**Comment by turecross321** [comment]
load earth: `/LITTLEBIGPLANETPS3_XML/slots/by?u=XX_noscper360_XX&pageStart=1&pageSize=40&gameFilterType=both&crosscontrol=true`

load lucky dip: `/LITTLEBIGPLANETPS3_XML/slots/lbp2luckydip?pageStart=1&pageSize=30&gameFilterType=both&seed=13&crosscontrol=true`

publish post request: `[HTTP] <slot type="user"> <name></name> <description></description> <icon>g10682</icon> <rootLevel>b8ae1dc4bce55de5d3616f076e7e8275995cdf05</rootLevel> <resource>909cb14f46cdea2d8ad3edf78358e41c2753a9d8</resource> <resource>a885c1e405faba29d9575d161b11677e1f5d1eca</resource> <resource>b8ae1dc4bce55de5d3616f076e7e8275995cdf05</resource> <resource>ce0c0d173603da3a852857550ecc15bb693c7823</resource> <resource>eab830d37da2acb092c4d43f46d3c0caf9a70ffe</resource> <location> <x>20452</x> <y>29231</y> </location> <initiallyLocked>false</initiallyLocked> <isSubLevel>false</isSubLevel> <isLBP1Only>false</isLBP1Only> <shareable>0</shareable> <background>107262</background> <links> </links> <internalLinks> </internalLinks> <leveltype></leveltype> <minPlayers>1</minPlayers> <maxPlayers>4</maxPlayers> <moveRequired>false</moveRequired> <vitaCrossControlRequired>true</vitaCrossControlRequired> </slot> `

**Comment by jvyden** [comment]
I would assume it fails because `<vitaCrossControlRequired>true</vitaCrossControlRequired>` ends up being seen as false. I'll implement this now.

**Comment by jvyden** [comment]
Try now @Arcadius2006 @turecross321

**Comment by turecross321** [comment]
Still getting the `There was a problem publishing your level. Please try again later.` message.

**Comment by jvyden** [comment]
And you're getting `<vitaCrossControlRequired>true</vitaCrossControlRequired>` in the upload request?

**Comment by jvyden** [comment]
Can someone send a level backup of a cross controller level?

**Comment by jvyden** [comment]
bump, I still need this

**Comment by turecross321** [comment]
Sure, but I don't know if you'll be able to publish it with the cross controller part included without uploading it in cross controller mode.

https://drive.google.com/file/d/11YQsW9htyQ-AzhyrjMKZ4gPfnnl7OpZR/view?usp=sharing

**Comment by Arcadius2006** [comment]
> Can someone send a level backup of a cross controller level?

you that i sent a backup in your discord DMs, right?
