### ISSUE TITLE
ProjectLighthouse: High code repetition

### ISSUE THREAD

**Issue by ghost** [LBPUnion/ProjectLighthouse#532]
**Describe the problem**
```
$ grep -rohF 'if (token == null) return' . | wc -w
455
```
_455_
**To Reproduce**
1. `$ grep -rohF 'if (token == null) return' . | wc -w`

**Expected behavior**
Maybe less than a dozen results.

**Screenshots**
![image](https://user-images.githubusercontent.com/32244961/197300951-35762192-802a-4653-ab2b-d889215b4a54.png)
**API Version(s)**
- It's not even versioned.

**Affected endpoint(s)**
All 146 of them.

**Additional context**
![image](https://media.tenor.com/siUF6_Z22eUAAAAC/wow.gif)

**Comment by daggintosh** [comment]
![2022-10-21_16-24](https://user-images.githubusercontent.com/32235163/197304492-c78a7984-65bd-42f2-9a27-21c5617318d1.png)
if (token == null) return go wHEEEE
