### ISSUE TITLE
account_id over online_id

### ISSUE THREAD

**Issue by ghost** [LBPUnion/ProjectLighthouse#533]
NP tickets has two fields relating to user: `account_id` (uint64_t that never changes) and `online_id` (string username)

The real LBP servers index users by `account_id` and `account_id` only, it only caches the result of `online_id` at login.

**Indexing users by `online_id` makes the server thinks it's two different users and not the same user if the user renames their online ID or Sony forcefully renaming their online ID for whatever reason.**

**Comment by sudokoko** [comment]
Fixed in #600
