### ISSUE TITLE
Privacy Settings

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#568]
The following privacy settings should be added to the website for users to configure:

- [x] Blocking other users
- [ ] Enabling/disabling profile comments
- [ ] Enabling/disabling level comments

There are also two in-game privacy settings we could choose to enable or disable as well. The options are to allow your levels and profile to be seen by everyone, only logged in users, or no one on the website. For public beta I'm not too concerned about these. Regardless of the user's choice, moderators should always be able to see the levels and profile on the website

**Comment by m88youngling** [comment]
Edited this issue to mention the in-game privacy settings for user profile and levels, but I feel this is less urgent than user blocking and comments and review disabling

**Comment by m88youngling** [comment]
I think for public beta, user blocking is probably sufficient. The rest can come later.

**Comment by Ratchet568** [comment]
💩
