### ISSUE TITLE
Newest Levels, Search, Lucky Dip, etc. display sublevels

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#58]
sublevels are levels that should only be accessible through level links and only visible to the publisher on their earth.
![image](https://user-images.githubusercontent.com/51852312/142060558-161e4b25-0444-4677-9387-ffa757f20cf9.png)

**Comment by Arcadius2006** [comment]
NOTE: THESE WORK FINE ON LBP2, THIS MUST BE SOMETHING VITA RELATED

**Comment by turecross321** [comment]
that is not true. they are visible in lbp2 too.
