### ISSUE TITLE
Plays on LBP Vita get counted in the database but do not display

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#60]
This is because it is displaying LBP2 plays as opposed to the newly implemented LBPVitaPlays paramater thingy in the database

**Comment by jvyden** [comment]
This might require quite a few changes to how Slots serialize, I cant see a clean way of doing this.

**Comment by turecross321** [comment]
can't wait for the non clean way of doing this

**Comment by turecross321** [comment]
This has only been partly fixed.

![image](https://user-images.githubusercontent.com/51852312/154916179-db3a40dc-2e50-4619-a96b-cde388361310.png)

While both the `Beaten x times` and `Played x times` counters now work, the `by x people` counter displays 0, no matter how many people have played it, and the same goes for the main counter with the plays icon.
![image](https://user-images.githubusercontent.com/51852312/154916520-604e339d-8d66-478f-ad10-6b9df6cfd995.png)
