### ISSUE TITLE
Redundancy In Displaying Scores on Website

### ISSUE THREAD

**Issue by indo2042** [LBPUnion/ProjectLighthouse#607]
When a group of players submit a score, it resubmits the score for x amount of times (x = the amount of players) 

![image](https://user-images.githubusercontent.com/114881121/209038388-530d86fb-64e6-4488-9fbb-8b7b54e5d2a1.png)

The most likely way of fixing this issue is to only accept the score of the host. Determining who's the host should be relatively simple, as it should use the same method used for Good Grief reports.

**Comment by Arcadius2006** [comment]
the OG game worked like this aswell though, but it showed seperate scoreboards depending on how many players were in your lobby

**Comment by Slendy** [comment]
Reopening until #622 is merged
