### ISSUE TITLE
Can't post on forum

### ISSUE THREAD

**Issue by RedRavenYouTube** [LBPUnion/ProjectLighthouse#611]
I cannot post on the forum
I cannot access the forum post feature. Oh an I had a question how can I log into Beacon? Do I need to use my Discord email? Because my Discord email is not the same as my PSN email.

**Comment by m88youngling** [comment]
Not the place for this. If you are having trouble with LBPUnion.com, please fill out a contact form. [](https://www.lbpunion.com/contact)
