### ISSUE TITLE
Password reset is broken

### ISSUE THREAD

**Issue by Ezoiar** [LBPUnion/ProjectLighthouse#631]
**Describe the bug**
Password reset being broken: It claims to have failed despite having matching new passwords.
This would also be an urgent problem for the 2023 USC beta team as this is an obstacle to become USC Scout, because it is possible that several would be too busy to finish it.

**To Reproduce**
1. any place where you can password reset

**Expected behavior**
A match of new passwords should make it as your new password.

**Screenshots**
![image](https://user-images.githubusercontent.com/36406820/211701793-981b67d9-0791-42ec-aa10-75de8914e17b.png)
Me typing 123456 as a prove.

**Environment Details**
 - OS: [Windows 11]
 - Browser and Version [Opera GX]

**Additional context**
Few people at the USC has reported that they have the same issue.

**Comment by Slendy** [comment]
Fixed by 7358a7ac4593a3971e255c65ffff11df84045f5e
