### ISSUE TITLE
Sublevels still appear on user pages

### ISSUE THREAD

**Issue by Kee7702** [LBPUnion/ProjectLighthouse#636]
**Describe the bug**
I published a level, but even when I view my profile on a incognito tab I can still see the level.

**To Reproduce**
1. Publish a level as a sublevel.
2. Go to your profile when signed out.
3. Check the levels tab to show the subleveled level.

**Expected behavior**
The level should not appear when signed out of the account which published it

**Screenshots**
No screenshot, but slot id 8491 is a sublevel but appears on user id 1029

**Environment Details**
 - OS: Windows 10
 - Browser and Version: Google Chrome 108

**Additional context**
This is only a visual bug, but given that slot ids can be found from this, it should be worth checking if the heart/queue api requests will work on levels you should be unable to access. Additionally, the Project Lighthouse webhook in the LBPUnion discord server will also post when subleveled levels are uploaded.

**Comment by sudokoko** [comment]
This was resolved by 69855406f500c00988e4e7cfc1614bf370b11297. Thanks for reporting this.
