### ISSUE TITLE
Broken sound in LBP2

### ISSUE THREAD

**Issue by LittleBigBr0** [LBPUnion/ProjectLighthouse#654]
**The broken sound of losing**
It sounds like tearing rubber or something like that

**To Reproduce**
1. Go to 'Moon'
2. Click on select the 'Interface' speaker
3. Scroll down to 'Failure sound'

**Expected  behavior**
I was expecting to hear the usual losing sound from LBP

**Screenshot**
Missing

**Game(s) affected**
 - Platform-PS3
 - Game-LBP2

**Additional context**
Very loud, presses on the ears. Moreover, this sound appears not only when playing the above.

**Comment by sudokoko** [comment]
Hi there! We appreciate you opening an issue, however this does not seem like a bug with Lighthouse-more so an issue with your game. You most likely have a corrupted audio file. Try reinstalling the game to see if that fixes the issue.

**Comment by Slendy** [comment]
Closing as this is not related to Lighthouse
