### ISSUE TITLE
Server does not validate MinPlayer and MaxPlayer on slot startPublish.

### ISSUE THREAD

**Issue by McMistrzYT** [LBPUnion/ProjectLighthouse#666]
**Describe the bug**
People can edit the MinPlayers and MaxPlayers properties of a slot to be anything (using third-party applications) and the server won't validate the values. This could possibly be abused to upload unplayable and crashing levels.

**To Reproduce**
1. Intercept traffic (using Fiddler or Wireshark)
2. Copy the request.
3. Edit the body to edit the property MinPlayers to anything different than the normal values.
4. Re-digest X-Digest-A.
5. Send.

**Expected behavior**
The server should block the invalid request.

**Game(s) affected**
 - Platform: All
 - Game: All

**Additional context**
This is not achieveable by normal means, but can be easily reproduced using bots and scripts.

**Comment by Slendy** [comment]
Addressed in 84325596eefecc280aa2b996f4f7ff7c09b4cb4b
