### ISSUE TITLE
Comments no longer show in-game after user blocking update

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#667]
**Describe the bug**
Comments fail to show up in game after the user blocking update was pushed. An exception is thrown in the log, shown below

[error.txt](https://github.com/LBPUnion/ProjectLighthouse/files/10713897/error.txt)

**To Reproduce**
1. Run Lighthouse on the latest build.
2. Click into a user with comments.
3. No comments appear in-game. They only appear on the website.

**Expected behavior**
Comments should appear in-game.

**Screenshots**

![image](https://user-images.githubusercontent.com/89745384/218263989-1859b9af-aa91-4242-9397-a972abc65834.png)

**Game(s) affected**
 - Platform: PS3)
 - Game: I've only tested this on LBP2.

**Comment by vilijur** [comment]
Just tested on LBP3 RPCS3 and LBP Vita, can confirm the bug affects these games too.

**Screenshots**
![image](https://user-images.githubusercontent.com/69403080/218265488-74b0eed3-1fec-4389-a93e-fe7b85f37512.png)
![Screenshot 2023-02-11 14-58-46](https://user-images.githubusercontent.com/69403080/218265504-1ba587ed-dc90-403b-83e2-97962c449eca.png)

**Comment by McMistrzYT** [comment]
Looks like it can't find the "IsBanned" property on the user. Will look into it.

**Comment by Slendy** [comment]
This issue was fixed in 75a5e706358a3ae6a9d0f2ca1941890b239b843e. The problem was from attempting to access a client-side-only field from a server-side query which generated an error resulting in the failure of the request.
