### ISSUE TITLE
High score on story side levels fails to upload

### ISSUE THREAD

**Issue by speedyman09** [LBPUnion/ProjectLighthouse#726]
**Describe the bug**
When getting to the scoreboard in a Vita story side level, the scoreboard will show "Uploading score failed!"

**To Reproduce**
1. Complete side level
2. Get to the scoreboard
3. Wait for scoreboard to contact server to upload high score
4. "Uploading score failed!"

**Expected behavior**
The score will upload to the gameserver and no issues would be caused

**Screenshots**
https://gyazo.com/03cd6385f94ec601d382b59caaa0b88a

**Game(s) affected**
 - Platform: PS Vita
 - Game: LBP Vita

**Comment by SammyGoesHowdy** [comment]
This happens for all story levels in LittleBigPlanet 2 and all story levels + community levels in LittleBigPlanet PlayStation Vita, not just the side levels in LittleBigPlanet PlayStation Vita. (Image from the DC Comics Premium Level Pack for LittleBigPlanet PlayStation Vita)

![image](https://user-images.githubusercontent.com/105883916/228630745-78fcea8f-0821-4382-9815-9e924b3501a9.png)

**Comment by speedyman09** [comment]
should i edit the issue

**Comment by Slendy** [comment]
Can you confirm if this issue was resolved by 8376928a6c692eb8e4c0879c611ed9586817cab9?

**Comment by speedyman09** [comment]
yes, it works now
