### ISSUE TITLE
/slot endpont is missing lots of information, appears to have been replaced with a much less detailed format

### ISSUE THREAD

**Issue by conn428** [LBPUnion/ProjectLighthouse#732]
**Describe the problem**
The /slot API endpoint returns significantly less info than it did before. The information returned now is essentially equivalent to a singular entry from the /slots endpoint, compared to before when it returned a lot more detail about the level than the /slots endpoint provided. Information such as the level description, creator ID, and labels/tags are now absent.

**Expected behavior**
More detailed information on a slot, such as level description, and author ID

**API Version(s)**
- /api/v1

**Affected endpoint(s)**
- /slot

**Additional context**
This change could very easily break any application that relies on this API for information. If this change is absolutely needed for whatever reason, it should be applied to a separate API version, such as something like /api/v2.

**Comment by Slendy** [comment]
This was an oversight on my part and not intended. I didn't design the old system so I didn't realize that the specific slot endpoint returned a more detailed response. The functionality should now be the same as before with the addition of the level's location being included.

**Comment by Slendy** [comment]
Fixed by f2dd41dd529df5bf68a26b12ed379d13d5d66f39
