### ISSUE TITLE
Levels do not update properly

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#734]
**Describe the bug**
Whenever you try to update any level, the only things that update are the level name, icon and description, with no changes made to the actual level.

**To Reproduce**
1. Publish level
2. Change something inside it
3. Republish the changed level
4. Check for changes inside the level

**Expected behavior**
The level updates just fine, with the in-level changes included

**Game(s) affected**
 - PS3, PSVita (Note: RPCS3 is yet to be tested)
 - Game LBP1, LBP2, LBPVita, LBP3

**Comment by Arcadius2006** [comment]
wasn't this solved already?

**Comment by sudokoko** [comment]
I have not occurrences of this issue recently. Though I'll inquire on it.

**Comment by Slendy** [comment]
Fixed in 5fbaa5df209fcfbb60783c7d58d5abd1571f7641
