### ISSUE TITLE
"By Author" picture display option doesn't work

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#746]
**Describe the bug**
If you choose to look at the pictures of a level and select "By Author", it will still show the pictures uploaded by other users

**To Reproduce**
1. Boot up LittleBIgPlanet 2 or 3,
2. Navigate to a published community level,
3. Press the Square button to show more options,
4. Navigate to one of the three displayed pictures and press the Cross button,
5. Compare the results of viewing both the "By Author" and "By Anyone" options.

**Expected behavior**
The page only shows pictures uploaded by the creator of the level

**Game(s) affected**
 - PS3, RPCS3, PSVita
 - LBP2, LBPV, LBP3

**Comment by Slendy** [comment]
Addressed by 8b0aed9a61feec5ff2dfacf86eb94ea44fbfa54f
