### ISSUE TITLE
Moderators and Administrators can create moderation cases on each other

### ISSUE THREAD

**Issue by sudokoko** [LBPUnion/ProjectLighthouse#770]
**Describe the bug**
Currently, if you are a moderator or administrator, you are able to issue moderation cases on another moderator or administrator. This causes an issue where the affected staff member has their permission level reset back to default.

**To Reproduce**
Steps to reproduce the behavior (you must be a mod/admin):
1. Go to a staff member's page, scroll down and click Ban User, for example.
2. Fill out the form and create the case.
3. Go to the moderation panel, and dismiss the case.
4. See that the affected staff member is now a default user.

**Expected behavior**
Either persisting the permission level when the case is dismissed, or simply not allowing moderators/admins to be banned until their permission level is manually set back to default.

**Screenshots (these tests were performed with permission.)**
https://github.com/LBPUnion/ProjectLighthouse/assets/68549366/19552a52-4da1-4ce6-9d6b-ca4d16da2dbd
https://github.com/LBPUnion/ProjectLighthouse/assets/68549366/28736a69-d3cf-4df4-821b-c16c04b01603

**Environment Details**
 - OS: MacOS 12.6.1
 - Browser and Version: Chrome 112.0.5615.137 (Official Build) (arm64)

**Comment by m88youngling** [comment]
Please don't hurt me

**Comment by Ezoiar** [comment]
MAYBE
