### ISSUE TITLE
Confirm Account Registration (Similar to confirming an email)

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#78]
When you register account, you should have to confirm the registration by logging onto the game (with the same psn/rpcn username as account name) and be on the same IP as the device which started the account registration.

This would be used to prevent people from registering with other people's names and other things like registering multiple accounts and filling up the db

**Comment by maks2011-2017** [comment]
psn: maks2011-2017

**Comment by m88youngling** [comment]
In our dev chat, we discussed using a custom announcements screen on first login to force the user to type in a random code on the website to verify they connected to the server successfully to complete account creation. Unverified users will be removed from the website after a period of time to prevent spam.

**Comment by m88youngling** [comment]
I am closing this issue in favor of a more detailed issue that expands on the questions that you suggested...I should have looked closer at this thread before I created the new one, sorry about that 

#500
