### ISSUE TITLE
Self-hearting through website

### ISSUE THREAD

**Issue by pikuse** [LBPUnion/ProjectLighthouse#803]
**Describe the bug**
It is currently possible to heart yourself through the website using the URL bar.

**To Reproduce**
1. Go to your profile page on the website
2. Add "/heart" after the user ID in the URL (e.g. beacon.lbpunion.com/user/yourid/heart)
3. Heart counter increases

**Expected behavior**
The heart counter should stay the same.

**Screenshots**
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/785e2496-b3b8-4e52-ace3-6753ff5ad033)
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/17b28171-af5d-4597-b591-f1561de294d7)
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/103dfb0f-7dbd-49e2-a0eb-97a9cf2af0e6)
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/051a79a2-2f8e-4901-9aef-3d2476fd29a4)

**Environment Details**
 - OS: Windows 10
 - Browser and Version: Google Chrome v114

**Additional context**
The reverse can be done by putting "/unheart" instead.
Version: project-lighthouse main@bf2e36e8 on Beacon

**Comment by Slendy** [comment]
Thanks for the report. This issue has been resolved in 425245fd07df30f6dff4801f9d00da57c27c931e. I have intentionally left the ability for users to unheart themselves for people who have already hearted themselves.
