### ISSUE TITLE
Add ability to disable comments through website

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#82]
These two things were among the main things that LBP.ME was used for since these aren't possible to do through the game. (As far as I'm aware at least lol)

**Comment by alkalinethunder** [comment]
I guess this defeats the purpose of the Blocked Persons screen in the PS3 Friends menu... 📦 

Shouldn't be too hard to implement on the website portion, but it might take some time to get blocked users to disappear in-game for the blocking user. Or maybe there's some endpoint the game uses to figure out what the blocked users are, not sure.

**Comment by jvyden** [comment]
Yeah, I would strongly prefer if people just blocked through PSN/RPCN.

**Comment by jvyden** [comment]
Closed in favor of #137
