### ISSUE TITLE
Sorting by LBP2 partially(?) works

### ISSUE THREAD

**Issue by pikuse** [LBPUnion/ProjectLighthouse#843]
**Describe the bug**
Sorting by LBP2 (in LBP2) doesn't hide LBP1 levels.

**To Reproduce**
1. Go to any category
2. Sort by "LittleBigPlanet 2"
3. The list stays the same. (exception: Lucky Dip)

**Expected behavior**
It will show a list of levels that are playable in LBP2.

**Screenshots**

![issue](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/c7d1384d-2363-46ca-bb8e-cea07c80a3b5)

**Game(s) affected**
 - Platform PS3
 - Game LBP2

**Additional context**
environment version: project-lighthouse main@25bb2ecf

**Comment by Slendy** [comment]
Should be fixed in 20a5fa6aa3ce1ffd67767ff502d643ae5259a5e9
