### ISSUE TITLE
Modded photos with future dates display at the top of the photos tab forever.

### ISSUE THREAD

**Issue by diediediebitch** [LBPUnion/ProjectLighthouse#844]
Because photos are ordered by date taken. Modded photos that have dates set in the future that havent happened yet will stay at the top of the photos page forever.

![image](https://github.com/LBPUnion/ProjectLighthouse/assets/137153247/0ee517d0-dc3a-40cc-9fce-25c78a056f14)

This photo is set in 2099 and has been at the top for about 4 days.

**Comment by Slendy** [comment]
This was a bug that was fixed in the past that must have been reintroduced at some point. It's been fixed in 1c00db53aef9813a3355676f0d41cfef91a14bf5 and the specific photo has been set to the correct timestamp.
