### ISSUE TITLE
Add the ability to block debug builds

### ISSUE THREAD

**Issue by sudokoko** [LBPUnion/ProjectLighthouse#871]
Created from #870 

<div type='discussions-op-text'>

<sup>Originally posted by **Oo1Toyo1oO** August 16, 2023</sup>
Since it's easier to copy uncopyable levels on debug builds and therefore levels could be stolen easier, and there are also a bunch of other reasons why you may not want people to be able to play on debug builds on a server, maybe even an option on which pre-release builds you allow or deny?</div>

**Comment by Oo1Toyo1oO** [comment]
Actually why just platform ps3? They exist for rpcs3?

**Comment by TorutheRedFox** [comment]
that's not possible
whatever you may do, if a player can run a debug build, they can get around any security measures you put in place by just spoofing a retail one

**Comment by sudokoko** [comment]
This was mentioned in the initial discussion. And yes, while this is true,
it might still be a useful feature to have.

**Comment by TorutheRedFox** [comment]
the issue is that legitimate usage of debug builds will get likely blocked out, while the illegitimate usage will continue since if they're going to go out of their way to boot a debug build to copy a level, they're gonna go out of their way to make it get around checks too

**Comment by sudokoko** [comment]
You make a fair point. I'll ask the rest of the team about this.

**Comment by sudokoko** [comment]
Closing this as it is ultimately your job as the instance administrator to enforce your instance's rules, other instances may not mind level copying - and this feature essentially would be a mute point for the reasons listed below ...

<div type='discussions-op-text'>

<sup>**TorutheRedFox** commented August 18th, 2023</sup>
the issue is that legitimate usage of debug builds will get likely blocked out, while the illegitimate usage will continue since if they're going to go out of their way to boot a debug build to copy a level, they're gonna go out of their way to make it get around checks too
</div>

Also in the original discussion you mentioned making modifications to a part of the login handler. This can be dangerous as it may potentially break or impair normal operation, cause unintended side effects, or data security issues. While there's nothing stopping you from doing this (assuming you're following AGPLv3 outlined in the [license](https://github.com/LBPUnion/ProjectLighthouse/blob/main/LICENSE)), I personally don't recommend it unless you get your code looked over by one of us. Feel free to reach out via Discord to get that done.

If you have any further concerns, I will leave the comments of this issue enabled for you to use.
