### ISSUE TITLE
Implement search filters

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/ProjectLighthouse#90]
There is a filter menu that you can activate using triangle (or R3 on LBP3), all of the options in it aren't functional currently and just show the standard level list without any alterations

**Comment by sudokoko** [comment]
This should be closed once/if #597 is finished.

**Comment by daggintosh** [comment]
> This should be closed once/if #597 is finished.

Refer to https://github.com/LBPUnion/ProjectLighthouse/issues/488#issuecomment-1399724468
