### ISSUE TITLE
Typo in source code link

### ISSUE THREAD

**Issue by pikuse** [LBPUnion/ProjectLighthouse#939]
**Describe the bug**
There is a missing colon in the link to the source code where it links to "https//github.com", and not "https://github.com".

**To Reproduce**
1. Go to the Lighthouse generated web page
2. Click on "Source Code"
3. Link does not work

**Expected behavior**
The link should go to "https://github.com"

**Screenshots**
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/98fc5475-3e9f-4fc6-adb1-b7031bec421e)
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/109040953/fcc45c1b-6f45-46f6-a8c7-b51cddac76a1)

**Environment Details**
 - OS: Windows 10
 - Browser and Version: Edge 118 Stable

**Additional context**
Environment version: project-lighthouse main@b8324d0

**Comment by Slendy** [comment]
This issue has been addressed by 0de5edca6e80ad4300890328a9b583d4ec868a3f. Thanks for reporting the issue.
